name: Automazione progetto Rubbez
on: [push]

jobs:
  Compilazione:
    runs-on: ubuntu-latest
    steps:
      - name: Installiamo cmake
        run: sudo apt install -y cmake
      - name: Clona emsdk
        run: git clone https://github.com/emscripten-core/emsdk.git
      - name: Install emsdk
        run: ./emsdk install latest
        working-directory: emsdk
      - name: Activate emsdk
        run: ./emsdk activate latest
        working-directory: emsdk
      - name: Aggiungere emsdk e emscripten alla variabile PATH
        run: source "/home/runner/work/robbez/robbez/emsdk/emsdk_env.sh"
      - run: /home/runner/work/robbez/robbez


