name: Automazione progetto Rubbez
on: [push]

jobs:
  Compilazione:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prima Automazione"
      - run: echo "Step di compilazione"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"
